export const SLIDER_IMAGES = [
  {
    img: "/images/slide1.png",
    text: "Villa",
    discount: "20% Off",
    title: "Luxury Villa",
    description: "Experience luxury with breathtaking views.",
    price: "$1000/day",
  },
  {
    img: "/images/slide2.png",
    text: "Mansion",
    discount: "15% Off",
    title: "Grand Mansion",
    description: "Opulent mansion for grand events.",
    price: "$1500/day",
  },
  {
    img: "/images/slide3.png",
    text: "House",
    discount: "10% Off",
    title: "Cozy House",
    description: "Modern amenities in a cozy setting.",
    price: "$500/day",
  },
  {
    img: "/images/slide4.png",
    text: "Cottage",
    discount: "25% Off",
    title: "Quaint Cottage",
    description: "Charming retreat surrounded by nature.",
    price: "$300/day",
  },
  {
    img: "/images/slide5.png",
    text: "Bungalow",
    discount: "30% Off",
    title: "Beach Bungalow",
    description: "Laid-back luxury with ocean views.",
    price: "$800/day",
  },
];

// export const sliderImages = [
//   {
//     img: "https://source.unsplash.com/600x600/?luxury+villa",
//     text: "Villa",
//     discount: "20% Off",
//     title: "Luxury Villa",
//     description: "Experience luxury with breathtaking views.",
//     price: "$1000/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?mansion",
//     text: "Mansion",
//     discount: "15% Off",
//     title: "Grand Mansion",
//     description: "Opulent mansion for grand events.",
//     price: "$1500/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?modern+house",
//     text: "House",
//     discount: "10% Off",
//     title: "Cozy House",
//     description: "Modern amenities in a cozy setting.",
//     price: "$500/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?cottage",
//     text: "Cottage",
//     discount: "25% Off",
//     title: "Quaint Cottage",
//     description: "Charming retreat surrounded by nature.",
//     price: "$300/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?beach+bungalow",
//     text: "Bungalow",
//     discount: "30% Off",
//     title: "Beach Bungalow",
//     description: "Laid-back luxury with ocean views.",
//     price: "$800/day",
//   },
// ];

// const sliderImages = [
//   {
//     img: "https://source.unsplash.com/600x600/?Villa",
//     text: "Villa",
//     discount: "20% Off",
//     title: "Luxury Villa",
//     description: "Experience luxury with breathtaking views.",
//     price: "$1000/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?Mansion",
//     text: "Mansion",
//     discount: "15% Off",
//     title: "Grand Mansion",
//     description: "Opulent mansion for grand events.",
//     price: "$1500/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?House",
//     text: "House",
//     discount: "10% Off",
//     title: "Cozy House",
//     description: "Modern amenities in a cozy setting.",
//     price: "$500/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?Cottage",
//     text: "Cottage",
//     discount: "25% Off",
//     title: "Quaint Cottage",
//     description: "Charming retreat surrounded by nature.",
//     price: "$300/day",
//   },
//   {
//     img: "https://source.unsplash.com/600x600/?Bungalow",
//     text: "Bungalow",
//     discount: "30% Off",
//     title: "Beach Bungalow",
//     description: "Laid-back luxury with ocean views.",
//     price: "$800/day",
//   },
// ];
